server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/app-db
    username: postgres
    password: 1996
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

minio:
  access:
    name: minioadmin
    secret: minioadmin
  url: http://localhost:9000
  bucket:
    datasets: ml-datasets
    algorithms: ml-algorithms
    models: ml-models
    predictions: ml-predictions
    results: prediction-results
    metrics: metrics
    parameters: parameters
